### ISSUE TITLE
Consider using native BarcodeDetector

### ISSUE THREAD

**Issue by jeznag** [KhaosArbiter/modern-react-qr-reader#3] opened 2021-03-04 03:28 UTC
The shape detection API can detect QR codes: https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector

Looks like it would be pretty straightforward to use this if it is available.

Would just need to send the image data to the barcodedetector instead of the worker
https://github.com/KhaosArbiter/modern-react-qr-reader/blob/master/src/index.js#L270

**Comment by KhaosArbiter** [comment] 2021-03-07 20:42
Currently this scans QR codes as intended, can you explain a bit clearer how this would improve the library?

**Comment by jeznag** [comment] 2021-03-08 03:39
would reduce the size of the package and potentially improve performance

**Comment by KhaosArbiter** [comment] 2021-03-16 14:55
This is definitely something to consider, I've put it under enhancements.  I haven't had the time yet to really get this library cleaned up just yet with other projects on my plate, so if anyone wants to do this first be my guest, otherwise I will begin this and other cleanup/enhancements as soon as I am able.

**Comment by nastassiadanilova** [comment] 2021-04-04 10:54
it doesn't supported well yet
https://caniuse.com/mdn-api_barcodedetector

**Comment by KhaosArbiter** [comment] 2021-04-04 11:34
No it is not you're right.  I am going to close this for now.

**Closed** 2021-04-04 11:35 UTC
Labels: enhancement
